### ISSUE TITLE
Convert to Rust

### ISSUE THREAD

**Issue by jgrund** [whamcloud/device-scanner#236]
Convert device-scanner, scanner-proxy, device-aggregator to use Rust.

### benefits

- Less tooling - currently dev needs: dotnet-core, nodejs, mono, paket. dev with Rust needs: rust.
- 0 Runtime dependencies - Rust spits out binaries, we can remove the dep we take on nodejs on the agent, which we currently have to maintain in our Copr.

- Faster, less memory usage: 
<img width="778" alt="bench-pipelined" src="https://user-images.githubusercontent.com/458717/46572030-604b1c00-c94d-11e8-9b68-28dc56dea9ae.png">

#### Current
<img width="962" alt="screen shot 2018-10-06 at 9 52 50 am" src="https://user-images.githubusercontent.com/458717/46572101-4eb64400-c94e-11e8-90b3-62e93eb198e1.png">

#### Rust
<img width="681" alt="screen shot 2018-10-06 at 9 53 22 am" src="https://user-images.githubusercontent.com/458717/46572102-4eb64400-c94e-11e8-89b6-faccd35cdc71.png">

- Threading plus safety guarantees between threads: https://doc.rust-lang.org/book/second-edition/ch16-00-concurrency.html

**Comment by johnsonw** [comment]
Seems like a no brainer to me 👍

**Comment by jgrund** [comment]
Tasks:

- [ ] Convert device-scanner to rust
  - [x] Add udev parsing
  - [x] Add mount parsing
  - [ ] Add Zed / libzfs parsing
- [x] Convert mount-emitter to rust
- [x] Convert udev-listener to rust
- [x] Convert scanner-proxy to rust
- [x] Convert device-aggregator to rust
- [ ] Convert zedlets to rust
- [x] Convert spec to package binaries
- [x] Update vagrantfile to build cluster
- [ ] Add high level integration tests
